REACTOR_RADIUS = 10

NUM_NUCLEI = 1000
NUCLEUS_INTERACTION_RADIUS = 0.25

INITIAL_NEUTRONS = 10
MEAN_FREE_PATH = 0.5

P_FISSION = 0.6
P_ABSORPTION = 0.25
P_SCATTER = 0.15

MEAN_SECONDARY_NEUTRONS = 2.5

MAX_STEPS = 100

# --- CONTROL ---
MAX_NEUTRONS = 300
MAX_SECONDARY_NEUTRONS = 2

TRAIL_LIFETIME = 25
MAX_TRAIL_PER_NEUTRON = 40
SIM_STEPS_PER_FRAME = 1